#ifndef _create_chat_subscription_invite_link_post_request_chat_id_TEST
#define _create_chat_subscription_invite_link_post_request_chat_id_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define _create_chat_subscription_invite_link_post_request_chat_id_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/_create_chat_subscription_invite_link_post_request_chat_id.h"
_create_chat_subscription_invite_link_post_request_chat_id_t* instantiate__create_chat_subscription_invite_link_post_request_chat_id(int include_optional);



_create_chat_subscription_invite_link_post_request_chat_id_t* instantiate__create_chat_subscription_invite_link_post_request_chat_id(int include_optional) {
  _create_chat_subscription_invite_link_post_request_chat_id_t* _create_chat_subscription_invite_link_post_request_chat_id = NULL;
  if (include_optional) {
    _create_chat_subscription_invite_link_post_request_chat_id = _create_chat_subscription_invite_link_post_request_chat_id_create(
    );
  } else {
    _create_chat_subscription_invite_link_post_request_chat_id = _create_chat_subscription_invite_link_post_request_chat_id_create(
    );
  }

  return _create_chat_subscription_invite_link_post_request_chat_id;
}


#ifdef _create_chat_subscription_invite_link_post_request_chat_id_MAIN

void test__create_chat_subscription_invite_link_post_request_chat_id(int include_optional) {
    _create_chat_subscription_invite_link_post_request_chat_id_t* _create_chat_subscription_invite_link_post_request_chat_id_1 = instantiate__create_chat_subscription_invite_link_post_request_chat_id(include_optional);

	cJSON* json_create_chat_subscription_invite_link_post_request_chat_id_1 = _create_chat_subscription_invite_link_post_request_chat_id_convertToJSON(_create_chat_subscription_invite_link_post_request_chat_id_1);
	printf("_create_chat_subscription_invite_link_post_request_chat_id :\n%s\n", cJSON_Print(json_create_chat_subscription_invite_link_post_request_chat_id_1));
	_create_chat_subscription_invite_link_post_request_chat_id_t* _create_chat_subscription_invite_link_post_request_chat_id_2 = _create_chat_subscription_invite_link_post_request_chat_id_parseFromJSON(json_create_chat_subscription_invite_link_post_request_chat_id_1);
	cJSON* json_create_chat_subscription_invite_link_post_request_chat_id_2 = _create_chat_subscription_invite_link_post_request_chat_id_convertToJSON(_create_chat_subscription_invite_link_post_request_chat_id_2);
	printf("repeating _create_chat_subscription_invite_link_post_request_chat_id:\n%s\n", cJSON_Print(json_create_chat_subscription_invite_link_post_request_chat_id_2));
}

int main() {
  test__create_chat_subscription_invite_link_post_request_chat_id(1);
  test__create_chat_subscription_invite_link_post_request_chat_id(0);

  printf("Hello world \n");
  return 0;
}

#endif // _create_chat_subscription_invite_link_post_request_chat_id_MAIN
#endif // _create_chat_subscription_invite_link_post_request_chat_id_TEST
